// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftslssyzlgbovlhpyrzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0c2xzc3l6bGdib3ZsaHB5cnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDY2MDEsImV4cCI6MjA2OTgyMjYwMX0.cF-4zWw0TRWbUjY4pgBGr3iCrRP4Z5EJnlH7bNqVgxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});